from typing import TypeAlias

Adjective: TypeAlias = str
Adposition: TypeAlias = str
Adverb: TypeAlias = str
Auxiliary: TypeAlias = str
Conjunction: TypeAlias = str
CoordinatingConjunction: TypeAlias = str
Determiner: TypeAlias = str
Interjection: TypeAlias = str
Noun: TypeAlias = str
Numeral: TypeAlias = str
Particle: TypeAlias = str
Pronoun: TypeAlias = str
ProperNoun: TypeAlias = str
Punctuation: TypeAlias = str
SubordinatingConjunction: TypeAlias = str
Symbol: TypeAlias = str
Verb: TypeAlias = str
Other: TypeAlias = str
EndofLine: TypeAlias = str
WhiteSpace: TypeAlias = str
